# This workflow builds and deploys the Vite project to GitHub Pages

name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch name (e.g., master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a suitable runner image

    permissions:
      contents: read # Allows the job to read the code from the repository
      pages: write # Allows the job to deploy to GitHub Pages
      id-token: write # Required for the deploy-pages action

    environment:
      name: github-pages # Specifies the deployment environment
      url: ${{ steps.deployment.outputs.page_url }} # Sets the URL of the deployed site

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use a recent LTS Node.js version

      - name: Install dependencies
        run: npm ci # Installs dependencies using package-lock.json/yarn.lock/pnpm-lock.yaml

      - name: Build Vite project
        run: npm run build # Runs the build command defined in your package.json

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Configures the GitHub Pages environment

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the build output directory (default is 'dist')
          path: './dist' # Make sure this path matches your Vite build output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploys the uploaded artifact to GitHub Pages